POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "john",
  "email": "john@gmail.com",
  "password": "1234"
}

POST http://localhost:3000/auth/login
Content-Type: application/json
{
  "email": "john@gmail.com",
  "password": "1234"
}