version: '3'
services:
  database-1:
    container_name: database-postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_PORT}:5432
    expose:
      - ${POSTGRESQL_PORT}
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data

  database-2:
    container_name: database-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: simple-auth
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    expose:
      - "3308"
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}" ]
      retries: 3
      timeout: 5s

volumes:
  simple-auth:
    driver: local